sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.cache/pip

install:
  # install aws cli
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - aws --version

script: mvn clean test -Dspring.profiles.active=test

before_deploy:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
