sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2

script: mvn clean test -Dspring.profiles.active=test

before_deploy: mvn package -DskipTests=true -Dmaven.javadoc.skip=true
deploy:
- provider: elasticbeanstalk
  app: springboot-angular2-tutorial
  env: prod
  bucket_name: elasticbeanstalk-ap-southeast-1-411701860491
  region: ap-southeast-1
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  zip_file: target/springboot-angular2-tutorial-0.1.0.war
  on:
    branch: master
