sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'

install:
  # install aws cli
  - sudo apt-get -y install python-pip
  - sudo pip install awscli

script: mvn clean test -Dspring.profiles.active=test

after_success:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # Switch AWS Role when ENV is prod
  - test "${ENV}" = "prod" && source scripts/switch-production-role.sh

before_deploy:
  # Create an archive to deploy
  - scripts/create-archives.sh
deploy:
  # upload jar and codedeploy scripts
  - provider: s3
    bucket: deploy-${ENV}.hana053.com
    region: ${AWS_DEFAULT_REGION}
    local_dir: .deploy
    upload-dir: micropost
    skip_cleanup: true
    on:
      branch: deploy/*
  # deploy by using codedeploy
  - provider: codedeploy
    bucket: deploy-${ENV}.hana053.com
    region: ${AWS_DEFAULT_REGION}
    key: micropost/codedeploy.tar.gz
    application: micropost-${ENV}
    deployment_group: web
    bundle_type: tgz
    on:
      branch: deploy/*

