sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'

script: mvn clean test -Dspring.profiles.active=test

before_deploy:
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  - scripts/create_codedeploy_archive.sh
deploy:
  - provider: s3
    bucket: web-condedeploy-${ENV}.hana053.com
    region: ${AWS_DEFAULT_REGION}
    local_dir: .deploy
    skip_cleanup: true
    on:
      branch: deploy/*
  - provider: codedeploy
    bucket: web-condedeploy-${ENV}.hana053.com
    region: ${AWS_DEFAULT_REGION}
    key: micropost-${TRAVIS_COMMIT}.tar.gz
    application: micropost-${ENV}
    deployment_group: web
    bundle_type: tgz
    on:
      branch: deploy/*

