version: 0.2

environment_variables:
  plaintext:
    S3_BUCKET: "beinghealer-springboot"

phases:
  pre_build:
    commands:
     - echo maven version is `mvn -version`
  build:
    commands:
     - echo Build started on `date`
     - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
     - echo Build ended on `date`
  post_build:
    commands:
     - echo Post-build started on `date`
     - aws s3 cp target s3://${S3_BUCKET} --recursive --region ap-south-1
     - echo Post-build completed on `date`

artifacts:
  files:
    - 'target/springboot-angular2-tutorial-0.1.0.jar'