phases:
  build:
    commands:
     - echo Build started on `date`
     - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
     - echo Build ended on `date`

artifacts:
  files:
    - 'target/springboot-angular2-tutorial-0.1.0.jar'