spring:
  main:
    banner-mode: 'OFF'
  profiles:
    active: dev
security:
  basic:
    enabled: false
endpoints:
  enabled: false
  health.enabled: true
management:
  context-path: /manage
app.jwt.secret: qwerty
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:log4jdbc:h2:./db/dev;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/springboot-angular2
    username: root
    password: root
  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: validate
  thymeleaf:
    cache: false
flyway:
  enabled: true
---
spring:
  profiles: dev2
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/springboot-angular2?useSSL=false
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
logging:
  config: classpath:logback-prod.xml
---
spring:
  profiles: test
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
flyway:
  enabled: false
server:
  port: 0
---
spring:
  profiles: stg
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mysql://${MYSQL_ENDPOINT}/ebdb?useSSL=false
    username: micropostuser
    password: ENC(jSxIbUwZQ5KgQJkOLGbYsZV83hH3oI0D)
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
logging:
  config: classpath:logback-prod.xml
app.jwt.secret: ENC(L4Y4hVbkFgZC3VFVWH28jTiCSSCBAx6xeM/nBSIahjrbc/JggbhTiKr2w9RLu9sx)
---
spring:
  profiles: prod
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mysql://${MYSQL_ENDPOINT}/ebdb?useSSL=false
    username: micropostuser
    password: ENC(eKw2P1jyrqKKs6KVg9Ql9iaJC8ve2kD8)
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
logging:
  config: classpath:logback-prod.xml
app.jwt.secret: ENC(t0NojUi8WhsSCti12Qj8CgzzrBA1Wt0PC9R1N5KvRltEcegGhxSy1zEmI7OxqzOA)
---
#Facebook
spring:
  social:
    facebook:
      app-id: 203064913467897
      app-secret: 559de0afd08faebfdd4b82fc9d54984d

#Twitter
twitter:
  consumer:
    key: CoxUiYwQOSFDReZYdjigBA
    secret: 2kAzunH5Btc4gRSaMr7D7MkyoJ5u1VzbOOzE8rBofs
---
rememberMe:
  privateKey: some_secret_word
---
signup-success: Signup Successful
